# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            曲忱 Chen Qu
tagline:          'A Jekyll theme'
description:      'Python, Android 开发者'
url:              http://chenqu.me
baseurl:          /

author:
  name:           'Chen Qu'
  url:            http://chenqu.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/prdwb
  
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
